//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandMember
    {
        public int FID { get; set; }
        public int BID { get; set; }
        public string Member { get; set; }
    
        public virtual BandBreakup BandBreakup { get; set; }
        public virtual Band Band { get; set; }
    }
}
