//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int RID { get; set; }
        public int SID { get; set; }
        public short Review1 { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
